### ISSUE TITLE
关于文件图标的大小设置

### ISSUE THREAD

**Issue by starsInEyes** [1217950746/Smile-Icons#1]
在使用您的文件图标时，给了我非常好的体验，已经非常完美了！
因为我对vscode知之甚少，我想稍微调大一点文件图标（不通过放大界面的方式），有什么好的办法吗？

**Comment by 1217950746** [comment]
这个没什么办法了，因为考虑到目录图标大小和普通图标大小的比例问题，所以现在选了一个比较合适的大小，高分屏下效果好
