### ISSUE TITLE
适配请求: .asm

### ISSUE THREAD

**Issue by vanishcode** [1217950746/Smile-Icons#3]
没看到汇编呀~ 最近一段时间在写汇编~ 请求适配~
很不错~
![](https://ws1.sinaimg.cn/large/006tKfTcgy1flfehmju4oj305y09ojrb.jpg)

**Comment by 1217950746** [comment]
不知道 .asm 是什么，可以的话，给我一下相关网站，我分析一下看看画成什么样

**Comment by vanishcode** [comment]
网站的话大概找了一下
http://blog.csdn.net/iijse/article/details/6251539
http://www.x86asm.com
https://baike.baidu.com/item/ASM/5646073?fr=aladdin

**Comment by 1217950746** [comment]
好的

**Comment by 1217950746** [comment]
已添加
