### ISSUE TITLE
请求适配 .tsx

### ISSUE THREAD

**Issue by cuixiaolu** [1217950746/Smile-Icons#4]
请求适配 .tsx

**Comment by 1217950746** [comment]
给我一下语言的相关链接

**Comment by cuixiaolu** [comment]
语言是 [Typescript](https://github.com/Microsoft/TypeScript)，而 [.tsx](https://www.typescriptlang.org/docs/handbook/jsx.html) 是用来和 React 的 .jsx 搭配使用。



刚看到这个消息，回复晚了，抱歉

**Comment by 1217950746** [comment]
懂了，这个已经包括在VSCode支持的语言里边了，现在会优先适配这些图标
