### ISSUE TITLE
请求适配 .hs .lhs .elm .rkt

### ISSUE THREAD

**Issue by yfzhe** [1217950746/Smile-Icons#5]
图标的设计很独特，有种耳目一新的感觉，在 v2 上看到就安装了。希望可以先把 VS Code 自带支持的语言都适配了吧。

这几个我自己用的比较多的：
- `.hs` 和 `.lhs` 是 Haskell 程序文件的扩展名 <https://www.haskell.org/>.
- `.elm` 是 Elm 的扩展名 <http://elm-lang.org/>.
- `.rkt` 是 Racket 的扩展名 <http://racket-lang.org/>.

再一个小意见：可以再多设一个基本图标，表示程序，对应到一些还没有设配的程序语言文件上；然后现在白底带问号的图标对应非程序的其他类型文件。现在写程序，图标上面一个问号感觉总是好难受😂

**Comment by 1217950746** [comment]
> 可以再多设一个基本图标，表示程序，对应到一些还没有设配的程序语言文件上
这个是做不到的
> 希望可以先把 VS Code 自带支持的语言都适配了吧
这个我尽量，还是大家需要的图标我优先适配就是了，一个人的精力有限

**Comment by 1217950746** [comment]
已添加
