### ISSUE TITLE
jsx和php以及ttf字体文件

### ISSUE THREAD

**Issue by gengfire** [1217950746/Smile-Icons#6]
jsx和php以及ttf字体文件还是显示"?"，请求添加，ps: 真的很赞

**Comment by 1217950746** [comment]
目前 VSCode 官方支持的一些会优先适配，插件现有的结构适配起来还是不太方便，我正在重写编译脚本，正在适配的有以下内容（其中可能包括以前已经有的）


.bat .cmd .clj .cljs .cljc .cljx .clojure .edn .coffee .cson .c .cpp .cc .cxx .hpp .hh .hxx .h .ino .inl .cs .csx .cake .css .diff .patch .rej .dockerfile .fs .fsi .fsx .fsscript .go .groovy.gvy .gradle .handlebars .hbs .hlsl .hlsli .fx .fxh .vsh .psh .cginc .compute .html .htm .shtml .xhtml .mdoc .jsp .asp .aspx .jshtm .volt .ejs .rhtml .ini .properties .gitconfig .cfg .conf .gitattributes .gitconfig .editorconfig .java .jav .jsx .js .mjs .pac .bowerrc .babelrc .json .bowerrc .jshintrc .jscsrc .eslintrc.babelrc .webmanifest .less .lua .mk .md .mdown .markdown .markdn .m .mm .pl .pm .pod .t .PL .psgi .nqp .php .phtml .ctp .pssc .psrc .jade .pug .py .rpy .pyw .cpy .gyp .gypi .r .rhistory .rprofile .rt .cshtml .rb .rbx .rjs .gemspec .rake .ru .erb .rs .scss .shader .sh .bash .bashrc .bash_aliases .bash_profile .bash_login .ebuild .install .profile .bash_logout .zsh .zshrc .zprofile.zlogin .zlogout .zshenv .sql .dsql .swift .ts .tsx .vb .brs .vbs .bas .xml .xsd .ascx .atom .axml .bpmn .config .cpt .csl .csproj .dita .ditamap .dtd .dtml .fsproj .fxml .iml .isml .jmx .launch .menu .mxml .nuspec .opml .owl .proj .props .pt .publishsettings .pubxml .rdf .rng .rss .shproj .storyboard .svg .targets .tld .tmx .vbproj .vcxproj .wsdl .wxi .wxl .wxs .xaml .xbl .xib .xlf .xliff .xpdl .xul .xoml .xsl .xslt .eyaml .eyml .yaml .yml
